### ISSUE TITLE
Unhandled error reading `indexOf` undefined  In Next JS Dev

### ISSUE THREAD

**Issue by aaronhayes** [arco-design/easy-email#114]
I'm getting the following error when running the example in development using Next.JS. 

I made a sample repo: https://github.com/aaronhayes/easy-email-next-js-error-sample
The error occurs on the `/editor` page when running under `yarn dev`  

And a codesandbox: https://codesandbox.io/s/amazing-zhukovsky-ik1yop?file=/pages/index.tsx 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Item$3 (index2.js?c838:18872:1)
    at renderWithHooks (react-dom.development.js?ac89:16175:1)
    at updateForwardRef (react-dom.development.js?ac89:20023:1)
    at beginWork (react-dom.development.js?ac89:22465:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:4210:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4274:1)
    at beginWork$1 (react-dom.development.js?ac89:27405:1)
    at performUnitOfWork (react-dom.development.js?ac89:26513:1)
    at workLoopSync (react-dom.development.js?ac89:26422:1)
    at renderRootSync (react-dom.development.js?ac89:26390:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25694:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
```

```
The above error occurred in the <CollapseItem> component:

    at Item$3 (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:18945:71)
    at div
    at Collapse (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:19178:61)
    at div
    at Item (webpack-internal:///./node_modules/easy-email-editor/lib/index.js:6892:17)
    at div
    at div
    at AttributesPanelWrapper (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:40721:113)
    at Page (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:40793:97)
    at PresetColorsProvider (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:39841:45)
    at SelectionRangeProvider (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:43247:94)
    at AttributePanel (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:43279:115)
    at div
    at TabPane$1 (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:28418:67)
    at div
    at div
    at div
    at TabContent (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:28976:25)
    at div
    at Tabs (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:29075:61)
    at div
    at div
    at Card (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:18425:61)
    at div
    at aside
    at Sider (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:16174:24)
    at section
    at Layout (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:16398:61)
    at ConfigProvider (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:7906:15)
    at SimpleLayout (webpack-internal:///./node_modules/easy-email-extensions/lib/index2.js:47702:104)
    at FormWrapper (webpack-internal:///./node_modules/easy-email-editor/lib/index.js:6505:3)
    at FocusBlockLayoutProvider (webpack-internal:///./node_modules/easy-email-editor/lib/index.js:6248:94)
    at ScrollProvider (webpack-internal:///./node_modules/easy-email-editor/lib/index.js:6031:69)
    at HoverIdxProvider (webpack-internal:///./node_modules/easy-email-editor/lib/index.js:5918:82)
    at BlocksProvider (webpack-internal:///./node_modules/easy-email-editor/lib/index.js:5865:82)
    at RecordProvider (webpack-internal:///./node_modules/easy-email-editor/lib/index.js:5972:83)
    at PreviewEmailProvider (webpack-internal:///./node_modules/easy-email-editor/lib/index.js:6392:76)
    at PropsProvider (webpack-internal:///./node_modules/easy-email-editor/lib/index.js:5948:11)
    at ReactFinalForm (webpack-internal:///./node_modules/react-final-form/dist/react-final-form.es.js:166:20)
    at EmailEditorProvider (webpack-internal:///./node_modules/easy-email-editor/lib/index.js:6482:11)
    at div
    at Editor
    at LoadableImpl (webpack-internal:///./node_modules/next/dist/shared/lib/loadable.js:101:38)
    at Editor
    at MyApp (webpack-internal:///./pages/_app.tsx:37:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20746)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23395)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:825:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:949:27)
```

**Comment by m-Ryan** [comment]
// next.config.js

Please remove `reactStrictMode: true`.

**Comment by aaronhayes** [comment]
awesome thanks!
