### ISSUE TITLE
Error while rendering the tutorial

### ISSUE THREAD

**Issue by scholz-timo** [arco-design/easy-email#120]
Hello your package looks promising for use inside of my project.

If you are intending to upgrade to 18.*.* please let me know.

**Comment by m-Ryan** [comment]
In fact, it supports react18, and used react@18 before. 

But react@18 requires react-router-dom@v6 and I can't use `Prompt` component  to check if the form is dirty before leaving the page. So I now downgrade to react@17. 

If you don't need it, you can upgrade to react@18.

Relatived: https://github.com/remix-run/react-router/issues/8139

**Comment by scholz-timo** [comment]
This is the package json file I am currently using:

```json
{
  "name": "source",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/react-fontawesome": "^0.1.18",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.8.3",
    "@types/jest": "^27.5.1",
    "@types/node": "^16.11.36",
    "@types/react": "^18.0.9",
    "@types/react-dom": "^18.0.5",
    "axios": "^0.27.2",
    "easy-email-core": "^3.2.3",
    "easy-email-editor": "^3.2.4",
    "easy-email-extensions": "^4.1.9",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-final-form": "^6.5.9",
    "react-router": "^6.0.0",
    "react-router-dom": "^6.0.0",
    "react-scripts": "4.0.3",
    "react-use-async-callback": "^2.1.1",
    "rxjs": "^7.5.5",
    "typescript": "^4.7.2",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/axios": "^0.14.0",
    "@types/react-router": "^5.1.18",
    "@types/react-router-dom": "^5.3.3",
    "utility-types": "^3.10.0"
  },
  "overrides": {
    "easy-email-core": {
      "react": "$react",
      "react-dom": "$react-dom"
    },
    "easy-email-editor": {
      "react": "$react",
      "react-dom": "$react-dom"
    },
    "easy-email-extensions": {
      "react": "$react",
      "react-dom": "$react-dom"
    }
  }
}
```

**Comment by m-Ryan** [comment]
Please update all.
```bash
"yarn add easy-email-core@latest easy-email-editor@latest easy-email-extensions@latest",
```

**Comment by scholz-timo** [comment]
Sorry to bother you again, but now it Is starting to render, but crashes while rendering:

item.js:35 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Item$3 (item.js:35:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at updateForwardRef (react-dom.development.js:20023:1)
    at beginWork (react-dom.development.js:22465:1)
    at beginWork$1 (react-dom.development.js:27381:1)
    at performUnitOfWork (react-dom.development.js:26513:1)
    at workLoopSync (react-dom.development.js:26422:1)
    at renderRootSync (react-dom.development.js:26390:1)
    at recoverFromConcurrentError (react-dom.development.js:25806:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25706:1)

**Comment by scholz-timo** [comment]
The code I am trying to run looks like this:

```ts
import { FunctionComponent } from "react";
import { BlockManager, BasicType } from 'easy-email-core';
import template from './template.json';

const { EmailEditor, EmailEditorProvider } = require('easy-email-editor');
const { SimpleLayout } = require('easy-email-extensions');

const initialValues = {
    subject: 'Welcome to Easy-email',
    subTitle: 'Nice to meet you!',
    content: {
        "type": "page",
        "data": {
          "value": {
            "breakpoint": "480px",
            "headAttributes": "",
            "font-size": "14px",
            "line-height": "1.7",
            "headStyles": [],
            "fonts": [],
            "responsive": true,
            "font-family": "lucida Grande,Verdana,Microsoft YaHei",
            "text-color": "#000000"
          }
        },
        "attributes": {
          "background-color": "#F4F4F4",
          "width": "600px",
          "css-class": "mjml-body"
        },
        "children": [
        ]
      }
};

const onSubmit = () => {

}

const MJMLEditor: FunctionComponent = () => {
    return (
        <EmailEditorProvider
          data={initialValues}
          height={'calc(100vh - 72px)'}
          autoComplete
          dashed={false}
          onSubmit={onSubmit}
        >
          {({ values }: any) => {
            return (
                <SimpleLayout>
                    <EmailEditor />
                </SimpleLayout>
            );
          }}
        </EmailEditorProvider>
      );
}

export default MJMLEditor;
```
