### ISSUE TITLE
Server side email sending

### ISSUE THREAD

**Issue by aaronhayes** [arco-design/easy-email#122]
How are we suppose to generate the html on the server side for actually sending emails? 

The documentation readme has this flow.

![image](https://user-images.githubusercontent.com/4180720/173231750-e60ca9e8-90ab-43a1-98f3-bb4fe1c7a1ff.png)

However, when trying to use the `JsonToMjml` function there are a few issues; the `easy-email-core` package has peer dependencies on `react`, `react-dom`, and `mjml-browser`. 

So I am getting a `window` undefined error: 

```
ReferenceError: window is not defined
     at Object.<anonymous> (/app/node_modules/mjml-browser/lib/index.js:1:230)
     at Module._compile (node:internal/modules/cjs/loader:1105:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
     at Object.require.extensions.<computed> [as .js] (/app/node_modules/ts-node/src/index.ts:1587:43)
     at Module.load (node:internal/modules/cjs/loader:981:32)
     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
     at Module.require (node:internal/modules/cjs/loader:1005:19)
     at require (node:internal/modules/cjs/helpers:102:18)
     at Module.<anonymous> (/app/node_modules/easy-email-core/lib/index.cjs.js:1:677)
     at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

**Comment by m-Ryan** [comment]
Please check this demo.
https://github.com/m-Ryan/easy-email-demo/blob/main/server.ts

**Comment by aaronhayes** [comment]
Perfect thanks
